### ISSUE TITLE
Expand $HOME in path, call expandpath(path) before putting path.

### ISSUE THREAD

**Issue by shamilcm** [xosnitc/xfs-interface#2]
void expandpath(char *path) // To expand environment variables in path
{
    char *rem_path = strdup(path);
    char *token = strsep(&rem_path, "/");
    sprintf(path,"%s/%s",getenv(++token)!=NULL?getenv(token):token-1,rem_path);
}

**Comment by sreerajsivadas** [comment]
Corrected
